"""
Django settings for trading_cards project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ipp)*p%n9szcr==hc+e%5s-q_4tcxemrr2lp!9=$h%bo%qgtif'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['tcg.timo-ramsauer.de', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'trading_cards',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trading_cards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trading_cards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'npm.finders.NpmFinder',
]

BOOTSTRAP3 = {
    "jquery_url": "https://code.jquery.com/jquery-3.3.1.min.js",
    "javascript_in_head": True,
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600

# Teamnames
TEAMNAMES = {
    '25_Rare': 'Rare',
    '24_Ref': 'Referee',
    '22_Volunteer': 'Volunteer',
    '04_Austria': 'Austria',
    '18_Belgium': 'Belgium',
    '05_Catalonia': 'Catalonia',
    '21_Comittee': 'Comittee',
    '06_Czech': 'Czech Republik',
    '19_Denmark': 'Denmark',
    '07_Finland': 'Finland',
    '03_France': 'France',
    '02_Germany': 'Germany',
    '08_Ireland': 'Ireland',
    '09_Italy': 'Italy',
    '17_Netherlands': 'Netherlands',
    '01_Norway': 'Norway',
    '10_Poland': 'Poland',
    '16_Scotland': 'Scotland',
    '20_Slovakia': 'Slovakia',
    '11_Slovenia': 'Slovenia',
    '23_Snitch': 'Snitch',
    '12_Spain': 'Spain',
    '13_Switzerland': 'Switzerland',
    '14_Turkey': 'Turkey',
    '15_UK': 'UK'
}

COLOR_NAME = {
    '25_Rare': '0,0,0,0',
    '24_Ref': '0,0,0,0',
    '22_Volunteer': '0,0,0,0',
    '04_Austria': '0,0,0,0',
    '18_Belgium': '0,0,0,0',
    '05_Catalonia': '0, 0.149, 1, 0',
    '21_Comittee': '0,0,0,0',
    '06_Czech': '0,0,0,0',
    '19_Denmark': '0,0,0,0',
    '07_Finland': '0,0,0,0',
    '03_France': '0, 0.827, 0.759, 0.070',
    '02_Germany': '0,0,0,0',
    '08_Ireland': '0,0,0,0',
    '09_Italy': '0,0,0,0',
    '17_Netherlands': '0,0,0,0',
    '01_Norway': '0,0,0,0',
    '10_Poland': '0, 0.909, 0.727, 0.137',
    '16_Scotland': '0,0,0,0',
    '20_Slovakia': '0.932, 0.518, 0, 0.364',
    '11_Slovenia': '1, 0.432, 0, 0.356',
    '23_Snitch': '0,0,0,0',
    '12_Spain': '0,0,0,0',
    '13_Switzerland': '0,0,0,0',
    '14_Turkey': '0,0,0,0',
    '15_UK': '0,0,0,0'
}

COLOR_POSITION = {
    '25_Rare': '12.83, 100, 35.05, 3.8',
    '24_Ref': '84.17, 67.05, 43.69, 41.03',
    '22_Volunteer': '99.3, 98.18, 13.11, 2',
    '04_Austria': '0, 0.827, 0.759, 0.070',
    '18_Belgium': '0, 0, 0, 1',
    '05_Catalonia': '0,0,0,0',
    '21_Comittee': '0,0,0,0',
    '06_Czech': '0.865, 0.452, 0, 0.505',
    '19_Denmark': '0, 0.939, 0.757, 0.223',
    '07_Finland': '1, 0.564, 0, 0.576',
    '03_France': '0,0,0,0',
    '02_Germany': '0,0,0,0',
    '08_Ireland': '0.858, 0, 0.367, 0.392',
    '09_Italy': '0, 0.791, 0.733, 0.192',
    '17_Netherlands': '0.762, 0.496, 0, 0.454',
    '01_Norway': '1,0.615,0,0.592',
    '10_Poland': '0,0,0,0',
    '16_Scotland': '0.994, 0.471, 0, 0.250',
    '20_Slovakia': '0,0,0,0',
    '11_Slovenia': '0,0,0,0',
    '23_Snitch': '0, 58.47, 85.23, 0.01',
    '12_Spain': '0,0,0,0',
    '13_Switzerland': '0, 0.798, 0.859, 0.16',
    '14_Turkey': '0, 0.955, 0.898, 0.109',
    '15_UK': '1, 0.712, 0, 0.509'
}
